@username=birgit
@password=geheim

###
GET http://localhost:8080/actuator
Authorization: Basic {{username}} {{password}}

###
GET http://localhost:8080/book
Authorization: Basic {{username}} {{password}}

###
GET http://localhost:8080/view
Authorization: Basic {{username}} {{password}}

###
@isbn=978-3836211161
GET http://localhost:8080/book/{{isbn}}
Authorization: Basic {{username}} {{password}}

###
GET http://localhost:8080/book?author=Rob
Authorization: Basic {{username}} {{password}}

###
POST http://localhost:8080/book/search
Authorization: Basic {{username}} {{password}}
Content-Type: application/json

{
"isbn": "978-3836211161",
"author": "Rob",
"slkdjlfas": "sdlskfh"
}

###
POST http://localhost:8080/book
Authorization: Basic {{username}} {{password}}
Content-Type: application/json

{
  "isbn": "222-3836211161",
  "author": "Birgit",
  "title": "My first book",
  "description": "A MUST read"
}