###
GET http://localhost:8080/book

###
GET http://localhost:8080/view

###
@isbn=978-3836211161
GET http://localhost:8080/book/{{isbn}}

###
GET http://localhost:8080/book?author=Rob

###
POST http://localhost:8080/book/search
Content-Type: application/json

{
"isbn": "978-3836211161",
"author": "Rob",
"slkdjlfas": "sdlskfh"
}

###
POST http://localhost:8080/book
Content-Type: application/json

{
  "isbn": "222-3836211161",
  "author": "Birgit",
  "title": "My first book",
  "description": "A MUST read"
}